name: "novaunit"

services:
 php:
    build: .docker
    restart: unless-stopped
    working_dir: /srv
    volumes:
        - .:/srv
        - ~/.composer:/home/composer/.composer
        - ./vendor:/srv/vendor:delegated
        - ./storage/xdebug:/tmp/xdebug:delegated
    environment:
        XDEBUG_MODE: '${XDEBUG_MODE:-off}'
        XDEBUG_CONFIG: '${XDEBUG_CONFIG:-client_host=host.docker.internal}'
    extra_hosts:
        - "host.docker.internal:host-gateway"

